# Generated by Django 3.1.3 on 2021-01-27 01:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='title')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Should not be edited manually, it is automaticallyupdated when save() is called on Entry', max_length=60)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('visits_count', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)], verbose_name='visits count')),
                ('html', models.TextField(blank=True, editable=False)),
                ('image', models.ImageField(null=True, upload_to=myblog.models.get_upload_path, verbose_name='image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, verbose_name='author email')),
                ('author_nickname', models.CharField(default='Anonymous', max_length=60, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='author nickname')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation_datetime')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.entry', verbose_name='entry')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['creation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Should not be edited manually, it is automaticallyupdated when save() is called on Category', max_length=60)),
                ('total_visits_count', models.IntegerField(default=0, editable=False)),
                ('entries', models.ManyToManyField(blank=True, to='myblog.Entry', verbose_name='entries')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
    ]
