# Generated by Django 3.1.3 on 2021-01-27 21:52

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
