# Generated by Django 3.1.3 on 2021-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Should not be edited manually, it is automaticallyupdated when save() is called on Category', max_length=60),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation datetime'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, help_text='Should not be edited manually, it is automaticallyupdated when save() is called on Entry', max_length=60),
        ),
    ]
