# Generated by Django 3.1.3 on 2021-01-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='test',
        ),
    ]
