# Generated by Django 3.1.3 on 2021-01-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='category',
            name='entries',
            field=models.ManyToManyField(blank=True, to='myblog.Entry', verbose_name='entries'),
        ),
    ]
