# Generated by Django 3.1.3 on 2021-01-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20210121_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_visits_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Should not be edited manually, it is automaticallyupdated when save() is called on Category', max_length=60),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Should not be edited manually, it is automaticallyupdated when save() is called on Entry', max_length=60),
        ),
    ]
