# Generated by Django 3.1.3 on 2021-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20210115_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_datetime'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_nickname',
            field=models.CharField(default='Anonymous', max_length=60, verbose_name='author nickname'),
        ),
    ]
