# Generated by Django 3.1.3 on 2021-01-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210129_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='html',
            field=models.TextField(blank=True, help_text="Editing manually is not recommended, as it's automatically populated when an app starts."),
        ),
    ]
