# Generated by Django 3.1.3 on 2021-01-24 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20210123_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_nickname',
            field=models.CharField(default='Anonymous', max_length=60, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='author nickname'),
        ),
    ]
